import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import { SessionProvider } from 'next-auth/react';
import Appcontext from '@/components/Appcontext';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '400', '500', '900', '300'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Appcontext>
          <main className="max-w-4xl mx-auto p-4">
            <Header />

            {children}

            <footer className="p-8 text-center text-gray-500">
              &copy; 2024 All rights reserved
            </footer>
          </main>
        </Appcontext>
      </body>
    </html>
  );
}
